solution/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  root to: redirect('/cats')
end

solution/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

solution/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  # .freeze renders a constant immutable.
  CAT_COLORS = %w(black white orange brown).freeze

  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w(M F)
  validates :birth_date, :color, :name, :sex, presence: true

  # Remember, has_many is just a method where the first argument is
  # the name of the association, and the second argument is an options
  # hash.
  has_many :rental_requests,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    time_ago_in_words(birth_date)
  end
end

solution/app/models/cat_rental_request.rb
class CatRentalRequest < ApplicationRecord
  # .freeze renders constants immutable
  STATUS_STATES = %w(APPROVED DENIED PENDING).freeze

  validates :cat_id, :end_date, :start_date, :status, presence: true
  validates :status, inclusion: STATUS_STATES
  validate :start_must_come_before_end
  validate :does_not_overlap_approved_request

  belongs_to :cat

  after_initialize :assign_pending_status

  def approve!
    raise 'not pending' unless self.status == 'PENDING'
    transaction do
      self.status = 'APPROVED'
      self.save!

      # when we approve this request, we reject all other overlapping
      # requests for this cat.
      overlapping_pending_requests.each do |req|
        req.update!(status: 'DENIED')
      end
    end
  end

  def approved?
    self.status == 'APPROVED'
  end

  def denied?
    self.status == 'DENIED'
  end

  def deny!
    self.status = 'DENIED'
    self.save!
  end

  def pending?
    self.status == 'PENDING'
  end

  private

  def assign_pending_status
    self.status ||= 'PENDING'
  end

  def overlapping_requests
    # ======================================
    #
    # Ranges can overlap in several ways:
    #
    #   |-----|       |-----|     |---|
    #       |-----|   |-----|   |-------|
    #     (2x)                    (2x)
    #
    # ======================================
    #
    # However, it is easier to think of the
    # two cases where they do not overlap:
    #
    #    [Case 1]
    #
    #        A              B
    #    |-------|      |-------|
    #    A(s)    A(e)   B(s)    B(e)
    #
    # The start point of B comes after the
    # end point of A. Thus: B(s) > A(e)
    #
    #
    #    [Case 2]
    #
    #        B              A
    #    |-------|      |-------|
    #    B(s)    B(e)   A(s)    A(e)
    #
    # The start point of A comes after the
    # end point of B. Thus: A(s) > B(e)
    #
    # ======================================
    #
    # Taking those two cases, we can say
    # there's no overlap when:
    #
    #   B(s) > A(e) || A(s) > B(e)
    #
    # ======================================
    #
    # We can negate this to get all cases
    # where there must be overlap:
    #
    #   !( B(s) > A(e) || A(s) > B(e) )
    #
    # Personally, I find this most clear.
    #
    # In order for overlap to occur, the
    # other range cannot be entirely before
    # it or entirely after it.
    #
    # ======================================
    #
    # You could distribute the negation:
    #
    #   !( B(s) > A(e) ) && !( A(s) > B(e) )
    #
    # And take it even further, making it
    # shorter, but perhaps less intuitive:
    #
    #   B(s) <= A(e) && A(s) <= B(e)
    #
    # ======================================

    # We want:
    # 1. A different request
    # 2. That is for the same cat.
    # 3. That overlaps.

    CatRentalRequest
      .where.not(id: self.id)
      .where(cat_id: cat_id)
      .where.not('start_date > :end_date OR end_date < :start_date',
                 start_date: start_date, end_date: end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where('status = \'APPROVED\'')
  end

  def overlapping_pending_requests
    overlapping_requests.where('status = \'PENDING\'')
  end

  def does_not_overlap_approved_request
    # A denied request doesn't need to be checked. A pending request
    # should be checked; users shouldn't be able to make requests for
    # periods during which a cat has already been spoken for.
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:base] <<
        'Request conflicts with existing approved request'
    end
  end

  def start_must_come_before_end
    return if start_date < end_date
    errors[:start_date] << 'must come before end date'
    errors[:end_date] << 'must come after start date'
  end
end

solution/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

solution/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def approve
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def create
    @rental_request = CatRentalRequest.new(cat_rental_request_params)
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      flash.now[:errors] = @rental_request.errors.full_messages
      render :new
    end
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end

  def new
    @rental_request = CatRentalRequest.new
  end

  private

  def current_cat_rental_request
    @rental_request ||=
      CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :end_date, :start_date, :status)
  end
end

solution/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:age, :birth_date, :color, :description, :name, :sex)
  end
end

solution/app/helpers/application_helper.rb
module ApplicationHelper
end

solution/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

solution/app/helpers/cats_helper.rb
module CatsHelper
end

solution/app/views/cat_rental_requests/new.html.erb
<h1>Create Rental Request</h1>

<%= render "shared/errors" %>

<form action="<%= cat_rental_requests_url %>" method="post">
  <label for="cat_rental_request_cat_id">Cat</label>
  <select name="cat_rental_request[cat_id]"
          id="cat_rental_request_cat_id">
    <option></option>
    <% Cat.all.each do |cat| %>
      <% selected = @rental_request.cat_id == cat.id %>
      <option <%= selected ? "selected" : "" %>
              value="<%= cat.id %>">
        <%= cat.name %>
      </option>
    <% end %>
  </select>
  <br>

  <label for="cat_rental_request_start_date">Start Date</label>
  <input
    type="date"
    name="cat_rental_request[start_date]"
    value="<%= @rental_request.start_date %>"
    id="cat_rental_request_start_date">
  <br>

  <label for="cat_rental_request_end_date">End Date</label>
  <input
    type="date"
    name="cat_rental_request[end_date]"
    value="<%= @rental_request.end_date %>"
    id="cat_rental_request_end_date">
  <br>

  <input type="submit">
</form>

solution/app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="cat_name">Name</label>
  <input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>">

  <label for="cat_birth_date">Birth date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="cat_birth_date"
    value="<%= cat.birth_date %>">
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
  <option disabled selected>-- select a color --</option>
    <% Cat::CAT_COLORS.each do |color| %>
      <option
        <%= cat.color == color ? "selected" : "" %>
        value="<%= color %>">
        <%= color.upcase %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">Male</label>
  <input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="cat_sex_female">Female</label>
  <br>

  <label>
    Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>

  <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

solution/app/views/cats/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? %>
        <form action="<%= approve_cat_rental_request_url(req) %>" method="post">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <input type="submit" value="Approve">
        </form>
        <form action="<%= deny_cat_rental_request_url(req) %>" method="post">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <input type="submit" value="Deny">
        </form>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

solution/app/views/cats/edit.html.erb
<h1>Edit My Cat</h1>
<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

solution/app/views/cats/index.html.erb
<h1>Cats upon cats!</h1>

<ul>
  <% @cats.each do |cat| %>
    <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
  <% end %>
</ul>

<a href="<%= new_cat_url %>">Create cat</a>

solution/app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

solution/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
  <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
    <tr>
      <td><%= attr_name %></td>
      <td><%= @cat.send(attr_name) %></td>
    </tr>
  <% end %>
</table>

<a href="<%= edit_cat_url(@cat) %>">Edit <%= @cat.name %></a>

<h2>Rental Requests</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
  </tr>
  <% @cat.rental_requests.order('start_date').each do |req| %>
    <%= render 'req_tr', req: req %>
  <% end %>
</table>

solution/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

solution/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>